// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmbhzkueystcanuokudp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tYmh6a3VleXN0Y2FudW9rdWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODU4MjYsImV4cCI6MjA1Njc2MTgyNn0.YpLQHXCiPu5Rrd-FgwQYdt26k-kSnQgNINTBB3xq0_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);